ffmpeg:
 root: D:/nginx/html/
 imagePath: /images
 imageType: jpg
 vframes: 1
 imageSize: 960x540
 startTime: 3
 size: 100
 debug: true
 path: E:/cmd_ff/x86_64/bin/
 recordPath: /video
 videoType: mp4












