ffmpeg:
 basePath: E:/cmd_ff/x86_64/bin/
 baseImagePath: E:/cmd_ff/x86_64/bin
 ImagePath: /image
 imageType: jpg
 vframes: 1
 imageSize: 960x540
 startTime: 3
 size: 100
 debug: true
 path: E:/cmd_ff/x86_64/bin/
 record: /video
 videoType: mp4












