server:
  port: 8899

ffmpeg:
 root: /home
 imagePath: /image
 imageType: jpg
 vframes: 1
 imageSize: 960x540
 startTime: 3
 size: 100
 debug: true
 path: /usr/local/ffmpeg/bin/
 recordPath: /video
 videoType: mp4












